import Vue from "vue";

import AerisMetadataCitation from "./submodules/aeris-metadata-citations/components/aeris-metadata-citations-register.js";
import AerisMetadataContacts from "./submodules/aeris-metadata-contacts/components/aeris-metadata-contacts-register.js";
import AerisMetadataDataPolicy from "./submodules/aeris-metadata-datapolicy/components/aeris-metadata-datapolicy-register.js";
import AerisMetadataDataLinks from "./submodules/aeris-metadata-data-links/components/aeris-metadata-data-links-register.js";
import AerisMetadataDescription from "./submodules/aeris-metadata-description/components/aeris-metadata-description-register.js";
import AerisMetadataDoi from "./submodules/aeris-metadata-doi/components/aeris-metadata-doi-register.js";
import AerisMetadataFormats from "./submodules/aeris-metadata-formats/components/aeris-metadata-formats-register.js";
import AerisMetadataInformations from "./submodules/aeris-metadata-information/components/aeris-metadata-information-register.js";
import AerisMetadataInformationLink from "./submodules/aeris-metadata-information-links/components/aeris-metadata-information-links-register.js";
import AerisMetadataInstruments from "./submodules/aeris-metadata-instruments/components/aeris-metadata-instruments-register.js";
import AerisMetadataModifications from "./submodules/aeris-metadata-modifications/components/aeris-metadata-modifications-register.js";
import AerisMetadataParameters from "./submodules/aeris-metadata-parameters/components/aeris-metadata-parameters-register.js";
import AerisMetadataPlatforms from "./submodules/aeris-metadata-platforms/components/aeris-metadata-platforms-register.js";
import AerisMetadataPublications from "./submodules/aeris-metadata-publications/components/aeris-metadata-publications-register.js";
import AerisMetadataQuicklookGallery from "./submodules/aeris-metadata-quicklook-gallery/components/aeris-metadata-quicklook-gallery-register.js";
import AerisMetadataSingleFileDonwload from "./submodules/aeris-metadata-single-file-download/components/aeris-metadata-single-file-download-register.js";
import AerisMetadataSpatialExtents from "./submodules/aeris-metadata-spatial-extents/components/aeris-metadata-spatial-extents-register.js";
import AerisMetadataTemporalExtents from "./submodules/aeris-metadata-temporal-extents/components/aeris-metadata-temporal-extents-register.js";
import AerisMetadataTitle from "./submodules/aeris-metadata-title/components/aeris-metadata-title-register.js";
import AerisMetadataYearSelectDownload from "./submodules/aeris-metadata-year-select-download/components/aeris-metadata-year-select-download-register.js";

Vue.use(AerisMetadataYearSelectDownload);
Vue.use(AerisMetadataTitle);
Vue.use(AerisMetadataTemporalExtents);
Vue.use(AerisMetadataSpatialExtents);
Vue.use(AerisMetadataSingleFileDonwload);
Vue.use(AerisMetadataQuicklookGallery);
Vue.use(AerisMetadataPublications);
Vue.use(AerisMetadataPlatforms);
Vue.use(AerisMetadataParameters);
Vue.use(AerisMetadataModifications);
Vue.use(AerisMetadataInstruments);
Vue.use(AerisMetadataInformationLink);
Vue.use(AerisMetadataInformations);
Vue.use(AerisMetadataFormats);
Vue.use(AerisMetadataDoi);
Vue.use(AerisMetadataDescription);
Vue.use(AerisMetadataDataLinks);
Vue.use(AerisMetadataDataPolicy);
Vue.use(AerisMetadataContacts);
Vue.use(AerisMetadataCitation);
